# Generated by Django 4.2.7 on 2023-12-31 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_professor_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('AppointmentDate', models.DateTimeField()),
                ('Purpose', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PetID', models.AutoField(primary_key=True, serialize=False)),
                ('PetName', models.CharField(max_length=255)),
                ('Species', models.CharField(max_length=255)),
                ('Breed', models.CharField(max_length=255)),
                ('BirthDate', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PrescriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('MedicationName', models.CharField(max_length=255)),
                ('Dosage', models.CharField(max_length=255)),
                ('PetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('TreatmentName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('PetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('VetID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('ClinicName', models.CharField(max_length=255)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='vet_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='ProfessorID',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='CourseID',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='StudentID',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='AssignmentID',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='StudentID',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='prescription',
            name='VetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.vet'),
        ),
        migrations.AddField(
            model_name='pet',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.vet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='PetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.pet'),
        ),
    ]
