# Generated by Django 4.2.7 on 2023-12-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_appointment_pet_prescription_treatment_vet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='PetID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vet',
            name='VetID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
