# Generated by Django 4.2.7 on 2023-12-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_pet_petid_alter_vet_vetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='Owner',
            field=models.CharField(max_length=255),
        ),
    ]
