# Generated by Django 4.2.7 on 2023-12-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='VetID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
